import Head from "next/head";

export default function Heads() {
  return (
    <Head>
      <title>Gereja Sidang Pantekosta DiIndonesia</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/img/logo.png" />
    </Head>
  );
}
